### ISSUE TITLE
Upload of image failed : /uploads directory doesn't exist (and it needs to be created manually, as a workaround))

### ISSUE THREAD

**Issue by fenix011** [YunoHost-Apps/listmonk_ynh#12]
### Describe the bug

*Failed media upload.*

### Context

- Hardware: *VPS bought online *
- YunoHost version: latest
- I have access to my server: *Through SSH *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no / *

### Steps to reproduce

- *Try to upload an image while implementing a newsletter campaign*
   

### Expected behavior

*File uploading*

### logs

 Listmonk error message says :

*Upload of image failed : /uploads directory doesn't exist (and it needs to be created manually, as a workaround))

### Workaround

*As said, '/uploads directory doesn't exist' (and it needs to be created manually, as a workaround))*

Thanks, thanks, thanks - Merci, merci, merci :-)

**Comment by navanchauhan** [comment]
Noted, will probably include a precreated directory as `/home/yunohost.app/listmonk` which will be backed up with the app backup process.

Leaving this issue open for now

**Comment by navanchauhan** [comment]
Rather than having a separate directory, which would require the user to change the default path in the UI, the package automatically creates the uploads folder and is automatically added to the backup
