### ISSUE TITLE
Can't install on arm64 board - No rule to make target 'dist'

### ISSUE THREAD

**Issue by pp-r** [YunoHost-Apps/listmonk_ynh#30]
### Describe the bug

*`Impossible d'installer listmonk : Une erreur est survenue dans le script d'installation de l'application` because `make: *** No rule to make target 'dist'.  Stop.`*

### Context

Try to install `listmonk` on a arm64 board through the webadmin.
- YunoHost version: 11.1.15
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain:
- Using an exotic ssh port

### Steps to reproduce

- *Try to install listmonk from webadmin on an arm64 board*
- *Try to install listmonk from CLI on an arm64 board*

### Expected behavior

*That the command `make` can target dist.*

### Logs

webadmin : https://paste.yunohost.org/raw/jiniqubapa

CLI : https://paste.yunohost.org/raw/zoqatezuwo

**Comment by navanchauhan** [comment]
Finally reproduced this issue. Investigating

**Comment by JacquelinDV** [comment]
Bonjour,
J'ai le même problème sur mon RPT 3 B avec yunohost 11.1.18

Le Log est à https://paste.yunohost.org/raw/koqufeyeze
Les lignes en cause paraissent être:
`2023-05-03 20:05:57,609: DEBUG - + make dist
2023-05-03 20:05:57,650: WARNING - make: *** Aucune règle pour fabriquer la cible « dist ». Arrêt.`

**Comment by navanchauhan** [comment]
#33 should fix this. Tested this on my own Pi (Install + Upgrade + SMTP setup)
