### ISSUE TITLE
Listmonk service often fails to start after server restart

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/listmonk_ynh#35]
### Describe the bug

After I restart my whole yunohost server, listmonk service often fails to restart. According to the logs the problem seems to be that the service tries to start before the DB is up again. When I start listmonk service manually after server is up again there is no issue. So, may be a solution would be to tell listmonk service to wait until DB is up again before restarting. I have a lot of systemd services running and listmonk is the only one with this problem. Thank you for help.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.3
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Just restart whole Yunohost server and wait if listmonk systemd service starts successfully.

### Expected behavior

Listmonk systemd service should start successfully after server restart.

### Logs
Here are the logs: https://paste.yunohost.org/lejehupavu

**Comment by navanchauhan** [comment]
Let me look into this over the weekend, been a bit too busy lately

**Comment by CodeShakingSheep** [comment]
It has already been fixed, see https://github.com/YunoHost-Apps/listmonk_ynh/commit/0c499382910c5d506d790f5b671cdfc92fbd4529 .
