### ISSUE TITLE
SMTP configuration guide

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/listmonk_ynh#4]
It would be really valuable to have some guidelines to setup the SMTP server, because I do not even know if it is mandatory to have it.

<img width="1440" alt="Screen Shot 2022-04-13 at 11 09 02 AM" src="https://user-images.githubusercontent.com/42862428/163142189-7ffa2bd9-4b34-44c2-b57b-a9484c322c3a.png">

**Comment by xplosionmind** [comment]
Follow the following setup:

![](https://user-images.githubusercontent.com/46165813/163185943-a45d967b-ed73-4697-bd52-5e65b040c192.png)

**Comment by navanchauhan** [comment]
@xplosionmind Do you think it would be better to explain the SMTP settings in the GitHub README?

The SMTP settings are not limited to just your server, for example I am using Mailjet as my SMTP relay for sending these campaign emails. So I need to enter the Mailjet config

**Comment by xplosionmind** [comment]
Even though with a general explanation, I believe the SMTP configuration process should be written on the README, yes.

**Comment by navanchauhan** [comment]
Alright 👍 I’ll update the docs today

**Comment by navanchauhan** [comment]
I am going to write an extensive documentation later this week before closing this issue

**Comment by navanchauhan** [comment]
Whoops, completely forgot about this, working on it right now

**Comment by navanchauhan** [comment]
created a PR for docs detailing different options to configure the SMTP settings (both using the local YunoHost server + something like Amazon SES). 

This page is available and linked on the README already

> YunoHost documentation for this app: https://yunohost.org/app_listmonk
